import { GenerateCaptionDto } from "../dto/ai.dto";

export class AiService {
  private readonly apiKey: string;

  constructor() {
    this.apiKey = process.env.GEMINI_API_KEY || "";
    if (!this.apiKey) {
      console.warn(
        "WARNING: GEMINI_API_KEY is not defined in the environment variables.",
      );
    }
  }

  async generateCaption(dto: GenerateCaptionDto): Promise<string> {
    if (!this.apiKey) {
      throw new Error("Gemini API key is not configured");
    }

    const {
      description,
      tone,
      length,
      platform,
      includeEmojis,
      includeHashtags,
    } = dto;

    const lengthInstruction =
      length === "Short"
        ? "one short punchy sentence or line"
        : length === "Medium"
          ? "a few engaging sentences"
          : "a detailed, comprehensive paragraph";

    const prompt = `You are an expert social media copywriter. Generate a caption for the following post:
- Platform: ${platform}
- Tone: ${tone}
- Length: ${length} (${lengthInstruction})
- Include Emojis: ${includeEmojis ? "Yes" : "No"}
- Include Hashtags: ${includeHashtags ? "Yes" : "No"}
- Description of the post: ${description}

Instructions:
1. Return ONLY the final caption. Do NOT wrap the caption in quotes.
2. Do NOT include markdown code blocks, introductory text, explanations, or any other conversational filler.
3. Tailor the style and hashtags to suit the ${platform} platform.`;

    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${this.apiKey}`;

    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: prompt,
              },
            ],
          },
        ],
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 1024,
        },
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Gemini API error: ${response.status} - ${errorText}`);
    }

    const data = (await response.json()) as any;
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
      throw new Error("No caption text generated by Gemini");
    }

    return generatedText.trim();
  }
}
